### ISSUE TITLE
Jokes

### ISSUE THREAD

**Issue by Hunter2807** [pgamerxdev/projects#16]
Hey! 

You have done a great work, but I would suggest you add more jokes **and** stories. If there is a way I can help, by either making a pill request, or something, then be sure to ping me. Otherwise, great work!

**Comment by pgamerxdev** [comment]
> Hey!
> 
> You have done a great work, but I would suggest you add more jokes **and** stories. If there is a way I can help, by either making a pill request, or something, then be sure to ping me. Otherwise, great work!

Hey there, 
There are actually over million jokes 
you can keep it asking "Tell me another joke" and it will
Same with the stories

You can still leave some stories/jokes here 🙂

**Comment by Hunter2807** [comment]
Oh cool. Because whenever I say it to tell any jokes, it always tells the same jokes. Thanks for the reply anyways. I will leave the jokes and stories here 😄

**Comment by pgamerxdev** [comment]
> Oh cool. Because whenever I say it to tell any jokes, it always tells the same jokes. Thanks for the reply anyways. I will leave the jokes and stories here 😄
😊

**Comment by Hunter2807** [comment]
Hey @pgamerxdev, apologies for the ping, but I wanted to know what should I do now for the API key? I think I got those in the last 2 weeks, so what I should do now? Do I need to do something in order to make those work in the future as well?

**Comment by pgamerxdev** [comment]
> Hey @pgamerxdev, apologies for the ping, but I wanted to know what should I do now for the API key? I think I got those in the last 2 weeks, so what I should do now? Do I need to do something in order to make those work in the future as well?

There is no loss in trying to register again 😄 
Go ahead and login with discord at https://api.pgamerx.com/register
