### ISSUE TITLE
Raw API

### ISSUE THREAD

**Issue by pgamerxdev** [pgamerxdev/projects#5]
We have raw API now! 
It will be hoisted on https://api.pgamerx.com
Currently there are 3 options
https://api.pgamerx.com/random/devjoke
https://api.pgamerx.com/random/pun
https://api.pgamerx.com/random/spooky

Others will be added soon

Anyone who can make a PY wrapper for this api, contact me

**Comment by pgamerxdev** [comment]
They are totally changed and will be updated soon
some of them can be found here - https://api.pgamerx.com/image/endpoints

**Comment by NightZan999** [comment]
Holy shit, this is insane. The source code on github?

**Comment by The-mortal-phoenix** [comment]
hey Pgamerx i can make a  py wrapper docs

**Comment by The-mortal-phoenix** [comment]
just give link to docs

**Comment by The-mortal-phoenix** [comment]
okay ill make a api wrapper for all 3 tomorrow
in 1 package and ill post it on pypi

**Comment by The-mortal-phoenix** [comment]
hey pgmerx do, something like reply['generated']  cause we can access json data with py much easier

**Comment by pgamerxdev** [comment]
> Holy shit, this is insane. The source code on github?

Haha not yet

**Comment by pgamerxdev** [comment]
> hey pgmerx do, something like reply['generated'] cause we can access json data with py much easier

There is already a wrapper
Intact there are 2 wrappers
Check the bottom of api branch

**Comment by The-mortal-phoenix** [comment]
checked so the api wrapper maker title is not up for grabs

**Comment by The-mortal-phoenix** [comment]
tell me when next comes out

**Comment by NightZan999** [comment]
> tell me when next comes out

I am also included :D

**Comment by pgamerxdev** [comment]
> checked so the api wrapper maker title is not up for grabs

Sorry, I don't understand what you mean by this

**Comment by NightZan999** [comment]
> > Holy shit, this is insane. The source code on github?
> 
> Haha not yet

Open source when?

**Comment by pgamerxdev** [comment]
> > > Holy shit, this is insane. The source code on github?
> > 
> > 
> > Haha not yet
> 
> Open source when?

Let's close this and create a new issue
